apiVersion: v1 
kind: Service 
metadata:
  name: deployment-service
spec:
  type: NodePort #loadbalancer clusterip
  selector:
    app: myapp
  ports: 
    - name: http 
      port: 80 
      targetPort: 80